### ISSUE TITLE
Array indices must be positive integers or logical values.

### ISSUE THREAD

**Issue by AlisaOmel** [porteralab/EZcalcium#15]
I am getting the error in the screenshot when ever I run Automated ROI detection. If I add manual initiation refinement, the neuron is correctly found, but the following error comes up after. I am not sure why it is failing. I am using MATLAB 2022a, I also tried MATLAB 2021b. I tried Ezcalcium V 3.0.1, 3.0, and 2.1.3 and I tried both Windows and Mac. I am also using the file created by the motion correction function. That successfully works on this file. It is also 8-bit. 

<img width="1379" alt="Screen Shot 2022-06-17 at 3 25 34 PM" src="https://user-images.githubusercontent.com/23412608/174389531-0b71721e-ac55-4203-a9c1-0b58e895c907.png">
<img width="523" alt="Screen Shot 2022-06-17 at 3 25 50 PM" src="https://user-images.githubusercontent.com/23412608/174389529-6b2e14c6-950f-4efa-b105-2979bfb52330.png">

**Comment by bodayw** [comment]
The reason is that you set "Estimated # of ROIs" to 1, which causes the `nr - options.nb + 1` to be -1, which is invalid as an index number.

This looks like a corner case that is not properly handled by CaImAn, and I'm not sure I would have time to look into and fix this upstream issue.

But an easy workaround would be to set Estimated # of ROIs to be at least 3 on the Settings panel of ROI Detection. Not sure what is your exact use case there, but typically there should be way more than just a handful of ROIs on the field of view...

**Comment by AlisaOmel** [comment]
Hello! Thank you for your response. I will try to set ROI to 3 and let you know how that goes! We have a driver line that labels our specific neurons of interest. There are 2 neurons, but since the penetration isn't 100% often we get calcium imaging results of only 1 neuron at a time.

**Comment by bodayw** [comment]
Ah I see, that makes sense. Although it might be a better strategy to target a higher number in ROI Detection just in case...but maybe the data is very clean in your case. Anyway you'll probably have to use the workaround to find a couple more ROIs and exclude them later for now.

**Comment by AlisaOmel** [comment]
Yes, we are very lucky because oue data is very clean, but we have a lot of motion which the motion correct really helps with. I used a sample with 4 neurons and set the ROI to 4. Now I am getting this error. I get past the stage it used to fail and got a Figure 2. Thank you very much for your help!

Error using cellfun
Input #2 expected to be a cell array, was double instead.

Error in order_ROIs (line 25)
    if isfield(P,'b'); P_or.b = cellfun(@times,P.b(srt),num2cell(nA(srt)'),'UniformOutput',false); end

Error in ez_roi_detect/RunROIDetectionButtonPushed (line 433)
                [A_or, C_or, S_or, ~] = order_ROIs(A2, C2, S2, P2); % order ROIs

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 138)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event) (line 63)
            newCallback = @(source, event)executeCallback(appdesigner.internal.service.AppManagementService.instance(), ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Button PrivateButtonPushedFcn.

**Comment by bodayw** [comment]
I couldn't figure out what's the problem here. The second input of `cellfun` is the output of `num2cell`, which should be a cell array by definition...seems weird.

Probably irrelevant, but maybe try increase the number of ROIs to detect even further? And, maybe try ROI Detection without "Use Neuron Classifier"?

If the problem persists, maybe share one of your data files that can produce this error so I can look into it on my side.
