### ISSUE TITLE
problem with running ez_roi_detect.mlapp

### ISSUE THREAD

**Issue by butterm** [porteralab/EZcalcium#17]
hi
I'm trying to run your code but I'm facing some issues...
1. Starting ROI detection for E:\My Drive\2P\Rachely\Data\allodynia\Burn_innocous\2021_08_19\Registered (Green)_Stack.tif
Undefined function 'read_file' for input arguments of type 'char'.

Error in ez_roi_detect/RunROIDetectionButtonPushed (line 337)
                Y = read_file(filename);
there is no read_file function, so I had to change it to:
                t = Tiff(filename,'r');
                Y = read(t);

2. Error using CNMFSetParms (line 158)
Ambiguous parameter name 'p' (pixels, plot_df, pause_time).

Error in ez_roi_detect/RunROIDetectionButtonPushed (line 345)
                options = CNMFSetParms(...                         % Check CNMFSetParms.m for more details

and I couldn't solve it.

thank you
![image](https://user-images.githubusercontent.com/34030062/189116130-49197c11-5722-468b-97b3-942ed35b6574.png)

**Comment by bodayw** [comment]
Hi,

It appears that you're using a very old version (before 2017) of CaImAn - that's why you don't have `read_file` and `p` was not yet introduced  in `CNMFSetParms` back then.

It should work once you update to the latest CaImAn. You can either use the original repo (https://github.com/flatironinstitute/CaImAn-MATLAB) or our fork - they're identical.

Cheers.
