### ISSUE TITLE
Problem with motion corrected tiff

### ISSUE THREAD

**Issue by Neuropharmacist** [porteralab/EZcalcium#18]
Hi!

I'm getting the following error during the generation of the motion corrected tiff stack.

Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 50838 (0xc696) encountered.' 
Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 50839 (0xc697) encountered.' 

The resulting file does not open/appears corrupted.  Advice would be much appreciated!

**Comment by bodayw** [comment]
Hi,

What is the format of your original data file? Is it TIFF?

I'm asking because this looks like what could happen when reading TIFF files, rather than writing (creating).

TIFF files can often have custom fields that LibTIFF (the software library included with MATLAB that deals with TIFF files) cannot recognize, thus the _warning_ messages - note that these are not _error_ messages.

These infamous "unknown field" warning messages when reading TIFFs can mostly be safely ignored.

Have you tried ignoring these warning messages and see if EZcalcium can finish the processing just fine? If not, the problem would be something else.

**Comment by Neuropharmacist** [comment]
Thank you for your answer!

I exported the 2P data as a series of individual color TIFF frames, then loaded in Image J and turned to BW and saved as 8bit stack for motion correction. Once the correction is done, the resulting file does not open in Windows Photo Viewer "file appears to be damaged, corrupted, or is too large" or in ImageJ "unsupported format or file not found".

**Comment by bodayw** [comment]
> color TIFF frames

I'm curious why would they be color, instead of gray scale (black and white)? Do you have multiple channels recorded during imaging? Or is it just single channel really, such that red, green and blue channels all have identical data?

EZcalcium can only handle single channel (gray scale) images.

> saved as 8bit stack

Is 8-bit also the bit depth of your original data recorded? As far as I know typically imaging software uses 16-bit, so you would want to use the same bit depth to avoid precision loss.

> does not open in Windows Photo Viewer

Windows photo viewer certainly cannot handle TIFFs with multiple images...

> in ImageJ "unsupported format or file not found"

So I think more details about your original data format and how exactly you converted them to TIFF stack that fed to EZcalcium would be helpful.

**Comment by Neuropharmacist** [comment]
> I'm curious why would they be color, instead of gray scale (black and white)? Do you have multiple channels recorded during imaging? Or is it just single channel really, such that red, green and blue channels all have identical data?

I recorded single channel but forgot to export in grayscale. Today I exported in grayscale and the same problem still exists.

> Windows photo viewer certainly cannot handle TIFFs with multiple images...

It sure seems like it can! But not after the motion correction step. See: https://www.dropbox.com/s/woyhbgebl3jsdmn/tiff%20mcor.png?dl=0

> So I think more details about your original data format and how exactly you converted them to TIFF stack that fed to EZcalcium would be helpful.

So I export the image frames from the Olympus software as grayscale tiffs, import to ImageJ as a sequence, and then Save As a tiff.

Here's a motion corrected ministack that no longer works https://www.dropbox.com/s/1ifsv0yp8x4362s/mini%20stack_mcor.tif?dl=0

**Comment by Neuropharmacist** [comment]
> I'm curious why would they be color, instead of gray scale (black and white)? Do you have multiple channels recorded during imaging? Or is it just single channel really, such that red, green and blue channels all have identical data?

By mistake, I originally exported RGB images, but I also did the same thing in grayscale but the issue is not resolved.

> Windows photo viewer certainly cannot handle TIFFs with multiple images...

Looks like it can, but not after mcor: https://www.dropbox.com/s/woyhbgebl3jsdmn/tiff%20mcor.png?dl=0

> So I think more details about your original data format and how exactly you converted them to TIFF stack that fed to EZcalcium would be helpful.

I saved as grayscale tiffs from Olympus software, imported as an image sequence to ImageJ and then exported as a tiff.

Here's a ministack before and after mcor:

https://www.dropbox.com/s/mbtvo200hpncww8/mini%20stack.tif?dl=0
https://www.dropbox.com/s/1ifsv0yp8x4362s/mini%20stack_mcor.tif?dl=0

**Comment by Neuropharmacist** [comment]
I got everything working even though the files no longer open in ImageJ after the mcor - they work fine for the analysis steps.

**Comment by bodayw** [comment]
> Looks like it can

Oh I see, then I'm wrong. 

> but not after mcor
> the files no longer open in ImageJ after the mcor

I guess it's due to the fact that EZcalcium always saves TIFF file with the "BigTIFF" format:
https://en.wikipedia.org/wiki/TIFF#BigTIFF

The 4 GB limit can be easily exceeded in modern 2-photon imaging, so I decided to always use BigTIFF, even when the file size is smaller than 4 GB. It's not something new - LibTIFF 4.0 was released more than 10 years ago - but it's still "new" enough that many applications don't support it yet.

But I would assume ImageJ should support it, given how often big TIFF files are handled by its users. I don't have much experience with ImageJ, though...You may want to look into maybe some plug-ins for ImageJ to add support for BigTIFF?

Maybe FIJI?
https://imagej.net/software/fiji/downloads
