### ISSUE TITLE
Including inactive neurons using EZcalcium automated ROI detection

### ISSUE THREAD

**Issue by bendbir** [porteralab/EZcalcium#23]
I work with iPSC neurons and I'm interested in ratio-ing active vs inactive neurons in a field of view.  Ideally I would detect all neurons using EZcalciums tools, assess whether or not they spontaneously depolarized in the time of the recording, and then bin them accordingly (active vs inactive).

I had two questions:
1) After testing on a few AVIs and tiff stacks, I've found that EZcalcium tends to omit some of the non-depolarizing cells appearing in the field of view (cells that are stably fluorescent for our neuron specific calcium indicator, but no change in fluorescence).  Is there anyway to overcome this through settings, or is depolarization and change in fluorescence over time a key component of the ROI selection algorithm? (is there any way to grab more inactive living neurons with automated ROI selection?)

2) In your experience, have you seen any significant differences between TIFF stack vs AVI input files?  Does the loss of information from TIFF to AVI have an impact?

Thank you for your help,
Ben

**Comment by bodayw** [comment]
>is depolarization and change in fluorescence over time a key component of the ROI selection algorithm?

That seems to be the case. One can manually add some more ROIs by enabling "Manual Initial Refinement", but that GUI is not very responsive and kind of destroys the idea of automatic batch processing.

>have you seen any significant differences between TIFF stack vs AVI input files? Does the loss of information from TIFF to AVI have an impact?

I guess you're talking about 16-bit vs 8-bit? Given that typically imaging software save data as 16-bit per channel images in TIFF, and AFAIK the AVI container only supports 8-bit per channel.

AFAIK people always keep and use the high bit-depth (16-bit) raw data. Though I have never tested how much difference it could make when compressing it down to 8-bit - it would depend on the SNR of data itself as well.

I think 16-bit is chosen just because it's the next step up from 8-bit (anything between 8-bit and 16-bit takes the same amount of memory as 16-bit) and is overkill in many scenarios. Storage is also relatively cheap, so no need to cut corners here, I guess.

**Comment by bendbir** [comment]
Thank you for the response and helpful information,

**Regarding manual ROI selection**: I'm finding when I try "manual initial refinement" and select ROIs in the field of view, they still do not appear in the final "included" category, which seems to defeat the purpose of manual selection step (I'm uncertain if they even appear in "excluded" category, so I can't tell if the manually selected are being saved or factored in.  I select them and press enter as described)

Do the manual selected ROIs still get included/excluded based the set ROI search criteria?  Would be great to know the best settings to manually select and not-exclude.  If the issue is the automatic final "exclusion" step, I'm struggling to determine the most generous criteria that ensures everything is included.

**Comment by bodayw** [comment]
Just realized I never replied...Yes, I have also seen manually added ROIs didn't "survive" the exclusion. My hunch is that CaImAn, and therefore EZcalcium, is mostly suitable for extracting activity of active neurons, but not for e.g. detecting inactive neurons etc. I don't recall successfully including all visible ROIs by tweaking the settings.
